;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

;;; Code:

(specifications->manifest
      '("adb"
        "ascii"
        "binutils"
        "binwalk"
        "buildah"
        "diffoscope"
        "difftastic" "emacs-difftastic"
        "pecus-emacs-next"
        "pecus-emacs-jwt"
        "guile-emacs"
        "emacs-autocrypt"
        "emacs-bluetooth"
        "emacs-buffer-env"
        "emacs-calfw"
        "emacs-citar" "emacs-citar-denote"
        "emacs-csv-mode"
        "emacs-dape"
        "emacs-dirvish"
        "emacs-disproject"
        "emacs-ednc"
        "emacs-ement"
        "emacs-emms" "opus-tools"
        "emacs-exwm"
        "emacs-filechooser"
        "emacs-forge"
        "emacs-graphql-mode"
        "emacs-helpful"
        "emacs-jinx"
        "emacs-jq-mode"
        "emacs-ligature"
        "emacs-lpy"
        "emacs-magit"
        "emacs-markdown-mode"
        "emacs-mentor"
        "emacs-nerd-icons"
        "emacs-nov-el"
        "emacs-org-caldav"
        "emacs-org-contacts"
        "emacs-org-vcard"
        "emacs-osm"
        "emacs-polymode" "emacs-polymode-org"
        "emacs-tempel" "emacs-eglot-tempel"
        "emacs-verb"
        "emacs-x509-mode"
        "file"
        "flac"
        "flashrom"
        "fontconfig"
        "font-google-noto-emoji"
        "font-iosevka-term-slab"
        "font-liberation"
        "font-wqy-zenhei"
        "freerdp"
        "gcc-toolchain"
        "gdb"
        "glibc"
        "gnuradio"
        "go" "emacs-go-mode"
        "gopls"
        "delve" ;; go debugger
        "go-minify"
        "graphviz" "emacs-graphviz-dot-mode"
        "guile-aws"
        "imagemagick"
        "iw"
        "java-eclipse-jdt-core"
        "libfaketime"
        "llvm"
        "clang"
        "lldb"
        "lua" "lua-language-server"
        "man-pages"
        "mariadb"
        "mit-krb5"
        "monero"
        "mpv" ;; "ffmpeg" propagated by "mpv"
        "mu"
        "mysql"
        "node-typescript"
        "openjdk"
        "openocd"
        "openssh"
        "openssl"
        "openvpn"
        "patch"
        "patchelf"
        "php"
        "pinentry-emacs"
        "poke" "emacs-poke-mode"
        "pwntools"
        "python-angr"
        "python-debugpy"
        "python-ipython"
        "python-pycryptodomex"
        "python-rassumfrassum"
        "python-requests"
        "python-scapy"
        "qemu"
        "retroarch" "libretro-dolphin-emu" "libretro-mupen64plus-nx"
        "rizin"
        "rr"
        "ruff"
        "rust" "emacs-rust-mode"
        "rust-analyzer" ;; "rust-clippy"
        "sage" "emacs-sage-shell-mode"
        "samba"
        "shellcheck"
        "emacs-shellcheck-flymake"
        "sigrok-cli"
        "socat"
        "sqlite"
        "squashfs-tools"
        "sshfs"
        "steam-client"
        "tiled"
        "tree-sitter-c"
        "tree-sitter-cpp"
        "tree-sitter-csv"
        "tree-sitter-comment"
        "tree-sitter-dockerfile"
        "tree-sitter-gitcommit"
        "tree-sitter-go"
        "tree-sitter-gomod"
        "tree-sitter-graphql"
        "tree-sitter-javascript"
        "tree-sitter-lua"
        "tree-sitter-make"
        "tree-sitter-org"
        "tree-sitter-php"
        "tree-sitter-powershell"
        "tree-sitter-sql"
        "tree-sitter-rust"
        "tree-sitter-xml"
        "unrar-free"
        "upx"
        "valkey"
        "wget"
        "wine64-staging"
        "wireguard-tools"
        "wireshark"
        "xrandr"
        "yt-dlp"
        "zbar"
        "zig" "emacs-zig-mode"
        "zls"))

;;; dev-phone-manifest.scm ends here
