Set-Alias -Name "cp"     -Value "rsync --archive --human-readable --info=progress2 --progress --verbose"
Set-Alias -Name "dd"     -Value "dd status=progress"
Set-Alias -Name "df"     -Value "df --human-readable"
Set-Alias -Name "dir"    -Value "emacsclient --create-frame --eval '(list-directory)' --no-wait"
Set-Alias -Name "edit"   -Value "emacsclient --create-frame --no-wait"
Set-Alias -Name "emacs"  -Value "emacsclient --create-frame --no-wait"
Set-Alias -Name "logout" -Value "emacsclient --eval '(server-delete-client)' & logout"
Set-Alias -Name "grep"   -Value "grep --color=auto"
Set-Alias -Name "mv"     -Value "rsync --archive --human-readable --info=progress2 --progress --remove-source-files --verbose"
Set-Alias -Name "nc"     -Value "socat -,rawer,escape=0x1d tcp:$@"
Set-Alias -Name "patch"  -Value "patch --backup --verbose"
Set-Alias -Name "ping"   -Value "ping -v"
Set-Alias -Name "ping6"  -Value "ping6 -v"
Set-Alias -Name "rm"     -Value "rm -I --one-file-system --verbose"
Set-Alias -Name "su"     -Value "su-rs"
Set-Alias -Name "sudo"   -Value "sudo-rs"
Set-Alias -Name "vdir"   -Value "emacsclient --create-frame --eval '(dired)' --no-wait"